version: "3"
services:
  front:
    container_name: susan-liff-next_front
    build:
      context: ./front
      dockerfile: Dockerfile
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000" # 開発用
      - "4000:4000" # 本番用
    volumes:
      - ./front:/app/:cached
      - node_modules_volume:/home/app/node_modules:delegated
      - build_volume:/home/app/build:nocopy
    command: yarn dev

volumes:
  node_modules_volume:
  build_volume:
